use std::fmt;

use crate::hir::types::BaseType;

/// A part of an interpolated string: either a literal text segment or an expression name.
#[derive(Debug, Clone, PartialEq)]
pub enum StringPart {
    Literal(String),
    Expr(String),
}

#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    /// 整数字面量。第二字段为 dtype：`42u8` → U8，`42i64` → I64，`42` → I32（默认）。
    IntLiteral(i64, BaseType),
    /// 浮点字面量。第二字段为 dtype：`3.14f32` → F32，`3.14f64` 或 `3.14` → F64。
    FloatLiteral(f64, BaseType),
    StringLiteral(String),
    ByteString(Vec<u8>),
    RawString(String),
    MultiLineString(String),
    InterpolatedString(Vec<StringPart>),
    CharLiteral(char),

    Identifier(String),
    Fn,
    Let,
    Mut,
    If,
    Else,
    Match,
    For,
    While,
    Do,
    Yield,
    Loop,
    Break,
    Continue,
    Return,
    Try,
    Use,
    Mod,
    Pub,
    Trait,
    Impl,
    Enum,
    Struct,
    Type,
    Self_,
    Async,
    Await,
    Spawn,
    Task,
    Shard,
    Node,
    Macro,
    Where,
    As,
    In,
    True,
    False,
    Move,

    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    EqEq,
    NotEq,
    Lt,
    Gt,
    LtEq,
    GtEq,
    AndAnd,
    OrOr,
    Not,
    Ampersand,
    Pipe,
    Caret,
    Shl,
    Shr,
    Assign,
    PlusAssign,
    MinusAssign,
    StarAssign,
    SlashAssign,

    LParen,
    RParen,
    LBracket,
    RBracket,
    LBrace,
    RBrace,
    Comma,
    Semicolon,
    Colon,
    Dot,
    DotDot,
    DotDotEq,
    DotDotDot,
    Arrow,
    FatArrow,
    ColonColon,

    QuestionMark,
    Hash,

    Eof,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Span {
    pub line: usize,
    pub col: usize,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}

impl fmt::Display for TokenKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            TokenKind::IntLiteral(n, _) => write!(f, "{}", n),
            TokenKind::FloatLiteral(n, _) => write!(f, "{}", n),
            TokenKind::StringLiteral(s) => write!(f, "\"{}\"", s),
            TokenKind::ByteString(b) => write!(f, "b\"{}\"", String::from_utf8_lossy(b)),
            TokenKind::RawString(s) => write!(f, "r\"{}\"", s),
            TokenKind::MultiLineString(s) => write!(f, "\"\"\"{}\"\"\"", s),
            TokenKind::InterpolatedString(parts) => {
                write!(f, "\"")?;
                for p in parts {
                    match p {
                        StringPart::Literal(s) => write!(f, "{}", s)?,
                        StringPart::Expr(e) => write!(f, "{{{}}}", e)?,
                    }
                }
                write!(f, "\"")
            }
            TokenKind::CharLiteral(c) => write!(f, "'{}'", c),
            TokenKind::Identifier(s) => write!(f, "{}", s),
            TokenKind::Fn => write!(f, "fn"),
            TokenKind::Let => write!(f, "let"),
            TokenKind::Mut => write!(f, "mut"),
            TokenKind::If => write!(f, "if"),
            TokenKind::Else => write!(f, "else"),
            TokenKind::Match => write!(f, "match"),
            TokenKind::For => write!(f, "for"),
            TokenKind::While => write!(f, "while"),
            TokenKind::Do => write!(f, "do"),
            TokenKind::Yield => write!(f, "yield"),
            TokenKind::Loop => write!(f, "loop"),
            TokenKind::Break => write!(f, "break"),
            TokenKind::Continue => write!(f, "continue"),
            TokenKind::Return => write!(f, "return"),
            TokenKind::Try => write!(f, "try"),
            TokenKind::Use => write!(f, "use"),
            TokenKind::Mod => write!(f, "mod"),
            TokenKind::Pub => write!(f, "pub"),
            TokenKind::Trait => write!(f, "trait"),
            TokenKind::Impl => write!(f, "impl"),
            TokenKind::Enum => write!(f, "enum"),
            TokenKind::Struct => write!(f, "struct"),
            TokenKind::Type => write!(f, "type"),
            TokenKind::Self_ => write!(f, "self"),
            TokenKind::Async => write!(f, "async"),
            TokenKind::Await => write!(f, "await"),
            TokenKind::Spawn => write!(f, "spawn"),
            TokenKind::Task => write!(f, "task"),
            TokenKind::Node => write!(f, "node"),
            TokenKind::Macro => write!(f, "macro"),
            TokenKind::Where => write!(f, "where"),
            TokenKind::As => write!(f, "as"),
            TokenKind::In => write!(f, "in"),
            TokenKind::True => write!(f, "true"),
            TokenKind::False => write!(f, "false"),
            TokenKind::Move => write!(f, "move"),
            TokenKind::Plus => write!(f, "+"),
            TokenKind::Minus => write!(f, "-"),
            TokenKind::Star => write!(f, "*"),
            TokenKind::Slash => write!(f, "/"),
            TokenKind::Percent => write!(f, "%"),
            TokenKind::EqEq => write!(f, "=="),
            TokenKind::NotEq => write!(f, "!="),
            TokenKind::Lt => write!(f, "<"),
            TokenKind::Gt => write!(f, ">"),
            TokenKind::LtEq => write!(f, "<="),
            TokenKind::GtEq => write!(f, ">="),
            TokenKind::AndAnd => write!(f, "&&"),
            TokenKind::OrOr => write!(f, "||"),
            TokenKind::Not => write!(f, "!"),
            TokenKind::Ampersand => write!(f, "&"),
            TokenKind::Pipe => write!(f, "|"),
            TokenKind::Caret => write!(f, "^"),
            TokenKind::Shl => write!(f, "<<"),
            TokenKind::Shr => write!(f, ">>"),
            TokenKind::Assign => write!(f, "="),
            TokenKind::PlusAssign => write!(f, "+="),
            TokenKind::MinusAssign => write!(f, "-="),
            TokenKind::StarAssign => write!(f, "*="),
            TokenKind::SlashAssign => write!(f, "/="),
            TokenKind::LParen => write!(f, "("),
            TokenKind::RParen => write!(f, ")"),
            TokenKind::LBracket => write!(f, "["),
            TokenKind::RBracket => write!(f, "]"),
            TokenKind::LBrace => write!(f, "{{"),
            TokenKind::RBrace => write!(f, "}}"),
            TokenKind::Comma => write!(f, ","),
            TokenKind::Semicolon => write!(f, ";"),
            TokenKind::Colon => write!(f, ":"),
            TokenKind::Dot => write!(f, "."),
            TokenKind::DotDot => write!(f, ".."),
            TokenKind::DotDotEq => write!(f, "..="),
            TokenKind::DotDotDot => write!(f, "..."),
            TokenKind::Arrow => write!(f, "->"),
            TokenKind::FatArrow => write!(f, "=>"),
            TokenKind::ColonColon => write!(f, "::"),
            TokenKind::QuestionMark => write!(f, "?"),
            TokenKind::Hash => write!(f, "#"),
            TokenKind::Eof => write!(f, "<EOF>"),
            TokenKind::Shard => write!(f, "shard"),
        }
    }
}
